### ISSUE TITLE
DigitizingTools causes QGis 3.0.3 to crash (on Win 10)

### ISSUE THREAD

**Issue by brunellop** [bstroebl/DigitizingTools#29] opened 2018-05-24 10:08 UTC
Hi!
I tried to install the Digitizing Tools plugin on the QGIS 3.0.3 version, but once installed it gives me the "QGIS Crashed" screen.

Crash ID: 17ad52ca73bb3113827324b00088cb8411bed55b

QObject::connect :
PyInit_QtCore :
PyFrame_New :
PyObject_Call :
PyInit_sip :
PyInit__gui :
PyCFunction_FastCallDict :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyErr_Occurred :
PyFunction_FastCallDict :
PyObject_CallFunctionObjArgs :
PyUnicode_AsUTF8AndSize :
PyFrame_New :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyErr_Occurred :
PyFunction_FastCallDict :
PyObject_CallFunctionObjArgs :
PyUnicode_AsUTF8AndSize :
PyFrame_New :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyErr_Occurred :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
instance :
instance :
QgsPluginRegistry::loadPythonPlugin :
QgisAppInterface::windowMenu :
QgisAppInterface::windowMenu :
QMetaObject::activate :
QStandardItemModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::dataChanged :
QStandardItemModel::itemChanged :
QStandardItem::setData :
QStandardItemModel::setData :
QSortFilterProxyModel::setData :
QStyledItemDelegate::editorEvent :
QAbstractItemView::selectionModel :
QAbstractItemView::edit :
QAbstractItemView::mouseReleaseEvent :
QListView::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyInit__gui :
PyCFunction_FastCallDict :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyErr_Occurred :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyErr_Occurred :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
instance :
instance :
QgisApp::rotatePointSymbols :
QgsPythonRunner::run :
QgisApp::showPluginManager :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.0.3-Girona
QGIS code revision: 8a899c8758
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by bstroebl** [comment] 2018-05-24 15:35
Sorry to read you have problems, however I have no Win10 available here for testing. Looks similar to #30 which I could not reproduce. Unload all other plugins and see if that helps.

**Comment by bstroebl** [comment] 2018-05-29 08:20
There are issues pending for Win7 (#30) and Mac (#28). In Win 7 deactivating all other plugins made DigitizingTools loadable. Could you please try if this is the case for you, too?
Which localization are you using?

**Comment by bstroebl** [comment] 2018-06-11 07:11
It may be possible that the Qgis2threejs plugin causes the issue. Please try if unlaoding Qgis2threejs solves the problem.

**Comment by brunellop** [comment] 2018-06-11 08:09
Thank you bstroebl!!!
I confirm that the problem is the plugin Qgis2threejs.
Before you install DigitizingTools and then eventually install Qgis2threejs.

**Comment by bstroebl** [comment] 2018-06-11 08:28
Shall I close the issue now?

**Closed** 2018-06-11 08:30 UTC

**Comment by brunellop** [comment] 2018-06-11 08:31
Yes hi!
