### ISSUE TITLE
Couldn't load plugin 'DigitizingTools' due to an error when calling its initGui() method in 3.30 version

### ISSUE THREAD

**Issue by sivansakthi** [bstroebl/DigitizingTools#61] opened 2023-03-15 03:03 UTC
Couldn't load plugin 'DigitizingTools' due to an error when calling its initGui() method 

TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python\qgis\utils.py", line 448, in startPlugin
    plugins[packageName].initGui()
  File "C:\Users/Inbaraj/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DigitizingTools\digitizingtools.py", line 104, in initGui
    self.moveSideByDistance = dtmovesidebydistance.DtMoveSideByDistance(self.iface, self.toolBar)
  File "C:\Users\Inbaraj\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools\dtmovesidebydistance.py", line 42, in __init__
    self.rb1 = QgsRubberBand(self.canvas,  False)
TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.30.0-'s-Hertogenbosch 's-Hertogenbosch, f186b8efe0e 

Python Path:
C:\Users/Inbaraj/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\google-street-view-layer-master
C:/PROGRA~1/QGIS33~1.0/apps/qgis/./python
C:/Users/Inbaraj/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Inbaraj/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.30.0\bin\python39.zip
C:\PROGRA~1\QGIS33~1.0\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib
C:\Program Files\QGIS 3.30.0\bin
C:\PROGRA~1\QGIS33~1.0\apps\Python39
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Inbaraj/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Inbaraj\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\Inbaraj\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:\Users/Inbaraj/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\excel_sync\libs\xlrd-1.2.0-py2.py3-none-any.whl
C:\Users/Inbaraj/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\excel_sync\libs\xlwt-1.3.0-py2.py3-none-any.whl
C:\Users/Inbaraj/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\joinmultiplelines
C:\Users\Inbaraj\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\Inbaraj\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:\Users\Inbaraj\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\Inbaraj\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:\Users\Inbaraj\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\Inbaraj\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:\Users\Inbaraj\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\Inbaraj\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools

**Comment by bstroebl** [comment] 2023-03-15 07:39
Duplicate of https://github.com/bstroebl/DigitizingTools/issues/60

**Closed by bstroebl** 2023-03-15 07:39 UTC
Labels: duplicate
